from django.conf.urls import url
from ExploreIceland import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/',views.about, name='about'),
    url(r'^attraction/',views.attraction, name='attraction'),
    url(r'^attractioncategory/attraction/glacier/',views.glacier, name='glacier'),
    url(r'^vatnajokull/',views.vatnajokull, name='vatnajokull'),
    url(r'^langjokull/',views.langjokull, name='langjokull'),
    url(r'^hofsjokull/',views.hofsjokull, name='hofsjokull'),
    url(r'^myrdalsjokull/',views.myrdalsjokull, name='myrdalsjokull'),
    url(r'^eyjafjallajokull/',views.myrdalsjokull, name='eyjafjallajokull'),
    url(r'^city/',views.city, name='city'),
    url(r'^activity/',views.activity, name='activity'),
    url(r'^attractioncategory/activity/icecaveexploring/',views.icecaveexploring, name='icecaveexploring'),
    url(r'^attractioncategory/activity/whalecruise/',views.whalecruise, name='whalecruise'),
    url(r'^wildanimal/',views.wildanimal, name='wildanimal'),
    url(r'^attractioncategory/wild-animal/whale',views.whale, name='whale'),
    url(r'^attractioncategory/wild-animal/seal/',views.seal, name='seal'),
    url(r'^attractioncategory/wild-animal/horse/',views.horse, name='horse'),
    url(r'^attractioncategory/wild-animal/puffin/',views.puffin, name='puffin'),
    url(r'^attractioncategory/wild-animal/reindeer/',views.reindeer, name='reindeer'),
    url(r'^attractioncategory/activity/horseriding/',views.horseriding, name='horseriding'),
    url(r'^attractioncategory/activity/diving/',views.diving, name='diving'),
    url(r'^attractioncategory/attraction/hotspring/',views.hotspring, name='hotspring'),
    url(r'^myvatnbath/',views.myvatnbath, name='myvatnbath'),
    url(r'^bluelagoon/',views.bluelagoon, name='bluelagoon'),
    url(r'^goldencircle/',views.goldencircle, name='goldencircle'),
    url(r'^kirkjufell/',views.kirkjufell, name='kirkjufell'),
    url(r'^attractioncategory/attraction/northernlights/',views.northernlights, name='northernlights'),
    url(r'^reynisfjara/',views.reynisfjara, name='reynisfjara'),
    url(r'^bardarbunga/',views.bardarbunga, name='bardarbunga'),
    url(r'^katla/',views.katla, name='katla'),
    url(r'^maelifell/',views.maelifell, name='maelifell'),
    url(r'^attractioncategory/city/egilsstadir/',views.egilsstadir, name='egilsstadir'),
    url(r'^attractioncategory/city/husavik/',views.husavik, name='husavik'),
    url(r'^attractioncategory/city/isafjordur/',views.isafjordur, name='isafjordur'),
    url(r'^attractioncategory/city/reykjavik/',views.reykjavik, name='reykjavik'),
    url(r'^attractioncategory/attraction/volcano/',views.volcano, name='volcano'),
    url(r'^attractioncategory/activity/hiking/',views.hiking, name='hiking'),
    url(r'^attractioncategory/activity/ski/',views.ski, name='ski'),
    url(r'^attractioncategory/attraction/waterfall/',views.waterfall, name='waterfall'),
    url(r'^attractioncategory/city/akureyri/',views.akureyri, name='akureyri'),
    url(r'^dettifoss/',views.dettifoss, name='dettifoss'),
    url(r'^dyjandi/',views.dyjandi, name='dyjandi'),
    url(r'^gullfoss/',views.gullfoss, name='gullfoss'),
    url(r'^seljalandsfoss/',views.seljalandsfoss, name='seljalandsfoss'),
    url(r'^skogafoss/',views.skogafoss, name='skogafoss'),
    url(r'^gallery/',views.gallery, name='gallery'),
    url(r'^contact/',views.contact, name='contact'),
    url(r'^attractioncategory/(?P<category_name_slug>[\w\-]+)/$',
        views.show_attractioncategory, name='show_attractioncategory'),
   url(r'search/', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    
    url(r'^restricted/', views.restricted, name='restricted'),
   url(r'^base_bootstrap/', views.base_bootstrap, name='base_bootstrap'),
]
