# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreIceland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExploreIceland.attractionCategory'),
        ),
    ]
