# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreIceland', '0003_auto_20180220_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractioncategory',
            options={'verbose_name_plural': 'attraction Categories'},
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attractionpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExploreIceland.attractionCategory'),
        ),
    ]
